### ISSUE TITLE
Implement sensor readings

### ISSUE THREAD

**Issue by mauricioaraldi** [mauricioaraldi/parkit#2]
We need the sensors to really read the distance between the car and objects and give tose reading to the user

**Comment by mauricioaraldi** [comment]
Talking with @henriquebecker91, decided to drop the idea of triangular sensors and adopted line of pixels sensor type ideia. Will implement twenty sensors: 5 for each corner of the car.

**Comment by henriquebecker91** [comment]
Someday I need to give the code a little of my time, XD.
